config/routes.rb
Rails.application.routes.draw do
    root :to => "users#home"
	resources :users
	resources :airplanes
	#resources :bookings
	get "ticket" => "airplanes#ticket", :as => "ticket"
	get "book" => "airplanes#book", :as => "book"
	get "logout" => "users#destroy_login", :as => "logout"
    get "login" => "users#verify_login", :as => "login"
    post "finalize" => "users#finalize", :as => "finalize"
    get "search" => "airplanes#search", :as => "search"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/airplane.rb
class Airplane < ApplicationRecord
	has_many :bookings
	validates_presence_of :name
	validates_uniqueness_of :name
	def self.search(search)
		if search
			@airplanes = Airplane.where( "name LIKE :query OR source LIKE :query OR destination LIKE :query OR category LIKE :query", query: "%#{search}%")

		else
			@airplanes = Airplane.all
		end
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
	belongs_to :airplane
	before_create :set_pnr
	def set_pnr
		self.pnr = SecureRandom.urlsafe_base64(6)
	end
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	validates_presence_of :email
	validates_uniqueness_of :email

	def self.authenticate(email, password)
		user = User.find_by(email: email).try(:authenticate, password)
		if user
			user
		else
			nil
		end
	end
end

app/models/user_admin.rb
class UserAdmin < User	
end

app/models/user_customer.rb
class UserCustomer < User	
end

app/controllers/airplanes_controller.rb
class AirplanesController < ApplicationController
	protect_from_forgery

	def new
		@airplane = Airplane.new
	end

	def create
		@airplane = Airplane.new(airplane_params)
		if @airplane.save
			redirect_to airplanes_path
		else
			flash.now.alert = "Something went wrong ! try again!!"
			render 'new'
		end
	end

	def index
		@airplanes = Airplane.all
	end

	def show
		@airplane = Airplane.find(params[:id])
	end

	def book
		@airplane = Airplane.find(params[:booking][:airplane_id])
		if @airplane
			@booking = Booking.create!(booking_params)
			if @booking.save
				NotificationMailer.notification_mailer(@booking,@airplane,current_user).deliver
				flash.now.notice = "Your booking was successfull, An email has been sent to you with the booking details."
				if @airplane.seats*50/100 < @airplane.bookings.count
			       @airplane.update_columns(price: @airplane.price + @airplane.price*10/100) 
			    end
			else
				flash.now.alert = "Seats are already filled"
				redirect_to root_path
			end
		else
			flash.now.alert = "Flight has been chancelled"
			redirect_to root_path
		end
	end


	def ticket
		respond_to do |format|
			format.html
			format.pdf do
        render pdf: "ticket"   # Excluding ".pdf" extension.
    end
end
end

def search
	@airplanes = Airplane.search(params[:search])
end


private

def airplane_params
	params.require(:airplane).permit(:name, :category, :seats, :rows, :source, :destination, :price)
end

def booking_params
	params.require(:booking).permit(:name, :status, :airplane_id, :pnr, :passport_id, :passenger1, :passenger2, :age)
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	helper_method :current_user

	private

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	protect_from_forgery
	before_action :verify_login, only: [:show, :index]

	def home
	end

	def new
		@user = UserCustomer.new
	end

	def create
		@user = UserCustomer.new(user_params)
		if @user.save
			#For now sending mail to single employee
			#We can loop email and send mail to all employees and can run it as delayed Job
			#NotificationMailer.notification_mailer(@employee).deliver
			redirect_to login_path, :notice => "You successfully Signed up, Please login to continue!"
		else
			flash.now.alert = "Email Already Taken" 
			render 'new'
		end
	end

	def show
		@user = UserCustomer.find(params[:id])
	end

	def index
		@user = UserCustomer.all
	end

	def verify_login
		if !current_user
			if params[:user] && params[:user][:email] && params[:user][:password]
				@user = User.authenticate(params[:user][:email], params[:user][:password])
			end
			if @user
				session[:user_id] = @user.id
				redirect_to airplanes_url, :notice => "Logged in!"
			else
				flash.now.alert = "Invalid email or password" if params[:user]
				render "verify_login"
			end
		end
	end

	def destroy_login
		session[:user_id] = nil
		redirect_to root_url, :notice => "Logged out!"
	end

	private
	
	def user_params
		params.require(:user).permit(:name, :email, :password)
	end

end

app/helpers/airplanes_helper.rb
module AirplanesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/airplanes/book.html.erb
<div class="container">
	<table class="table table-striped">
		<thead>
			<tr>
				<th scope="col">Details</th>
				<th scope="col">Provided Info</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>Customer Name</td>
				<td><%= @booking.name if @booking.name %></td>
			</tr>
			<tr>
				<td>Customer Age</td>
				<td><%= @booking.age if @booking.age %></td>
			</tr>
			<tr>
				<td>Customer ID</td>
				<td><%= @booking.passport_id if @booking.passport_id %></td>
			</tr>
			<tr>
				<td>PNR</td>
				<td><%= @booking.pnr if @booking.pnr %></td>
			</tr>
			<tr>
				<td>Airline</td>
				<td><%= @airplane.name if @airplane.name %></td>
			</tr>
			<tr>
				<td>category</td>
				<td><%= @airplane.category if @airplane.category %></td>
			</tr>
			<tr>
				<td>Booked From</td>
				<td><%= @airplane.source if @airplane.source %></td>
			</tr>
			<tr>
				<td>Booked Upto</td>
				<td><%= @airplane.destination if @airplane.destination %></td>
			</tr>
			<tr>
				<td>Amount Paid</td>
				<td><%= @booking.airplane.price if @booking.airplane.price %></td>
			</tr>
		</tbody>
	</table>
</div>
<%= link_to 'Create PDF document', ticket_path(@booking, :format => :pdf) %>

app/views/airplanes/index.html.erb
<div class="container">
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col"><img src="https://img.icons8.com/wired/24/000000/numbered-list.png"></th>
        <th scope="col">Name</th>
        <th scope="col">category</th>
        <th scope="col">Source</th>
        <th scope="col">Destination</th>
        <th scope="col">Price</th>
        <%if current_user %>
        <th scope="col">Book <i class="fa fa-plane" style="font-size:24px;color: green;"></i></th>
        <%end%>
      </tr>
    </thead>
    <tbody>
      <% @airplanes.each_with_index do |airplane,index| %>
      <tr>
        <th scope="row"><%=index+1%></th>
        <td><%= airplane.name if airplane.name%></td>
        <td><%= airplane.category if airplane.category %></td>
        <td><%= airplane.source if airplane.source %></td>
        <td><%= airplane.destination if airplane.destination %></td>
        <td><%= airplane.price if airplane.price %></td>
        <%if current_user%>
        <td>
          <%= link_to "Book Now", airplane_path(airplane), :class => 'btn btn-success' %>
        </td>
        <%end%>
      </tr>
      <%end%>
    </tbody>
  </table>

  <div class="row">
    <%if current_user && current_user.type == "UserAdmin"%>
    <div class="col">
      <%= link_to "New Flight", new_airplane_path, :class => 'btn btn-warning btn-block' %>
    </div>
    <%end%>
    <%if !current_user%>
    <div class="col">
      <p class="text-danger text-center"><strong>Please login to book flights.</strong></p>
      <%= link_to "Login", login_path, :class => 'btn btn-success btn-block' %>
    </div>
    <%end%>

  </div>

</div>

app/views/airplanes/new.html.erb
<br>
<div class="container">
	<div class="login-form">
		<%= form_tag(airplanes_path, method: "new") do %>
		<div class="sign-in-htm">
			<div class="group">
				<label for="name" class="label">Name</label>
				<%= text_field_tag "airplane[name]","",{class: "input"} %>
			</div>
			<div class="group">
				<label for="category" class="label">Category</label>
				<%= text_field_tag "airplane[category]","",{class: "input"} %>
			</div>
			<div class="group">
				<label for="seats" class="label">Seats</label>
				<%= text_field_tag "airplane[seats]","",{class: "input"} %>
			</div>
			<div class="group">
				<label for="rows" class="label">Rows</label>
				<%= text_field_tag "airplane[rows]","",{class: "input"} %>
			</div>
			<div class="group">
				<label for="source" class="label">Source</label>
				<%= text_field_tag "airplane[source]","",{class: "input"} %>
			</div>
			<div class="group">
				<label for="destination" class="label">Destination</label>
				<%= text_field_tag "airplane[destination]","",{class: "input"} %>
			</div>
			<div class="group">
				<label for="price" class="label">Price</label>
				<%= text_field_tag "airplane[price]","",{class: "input"} %>
			</div>
			<div class="group">
				<%= submit_tag "Create", {class: "button"} %>
			</div>
			<div class="hr"></div>
		</div>
		<%end%>	
	</div>
</div>

app/views/airplanes/search.html.erb
<div class="container">
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col"><img src="https://img.icons8.com/wired/24/000000/numbered-list.png"></th>
        <th scope="col">Name</th>
        <th scope="col">category</th>
        <th scope="col">Source</th>
        <th scope="col">Destination</th>
        <th scope="col">Price</th>
        <%if current_user %>
        <th scope="col">Book <i class="fa fa-plane" style="font-size:24px;color: green;"></i></th>
        <%end%>
      </tr>
    </thead>
    <tbody>
      <% @airplanes.each_with_index do |airplane,index| %>
      <tr>
        <th scope="row"><%=index+1%></th>
        <td><%= airplane.name if airplane.name%></td>
        <td><%= airplane.category if airplane.category %></td>
        <td><%= airplane.source if airplane.source %></td>
        <td><%= airplane.destination if airplane.destination %></td>
        <td><%= airplane.price if airplane.price %></td>
        <%if current_user%>
        <td>
          <%= link_to "Book Now", airplane_path(airplane), :class => 'btn btn-success' %>
        </td>
        <%end%>
      </tr>
      <%end%>
    </tbody>
  </table>

  <div class="row">
    <%if current_user && current_user.type == "UserAdmin"%>
    <div class="col">
      <%= link_to "New Flight", new_airplane_path, :class => 'btn btn-warning btn-block' %>
    </div>
    <%end%>
    <%if !current_user%>
    <div class="col">
      <p class="text-danger text-center"><strong>Please login to book flights.</strong></p>
      <%= link_to "Login", login_path, :class => 'btn btn-success btn-block' %>
    </div>
    <%end%>

  </div>

</div>

app/views/airplanes/show.html.erb
<div class="container">
	<table class="table table-striped">
		<thead>
			<tr>
				<th scope="col">Airline</th>
				<th scope="col">Category</th>
				<th scope="col">Source</th>
				<th scope="col">Destination</th>
				<th scope="col">Price</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td><%= @airplane.name if @airplane.name %></td>
				<td><%= @airplane.category if @airplane.category %></td>
				<td><%= @airplane.source if @airplane.source %></td>
				<td><%= @airplane.destination if @airplane.destination %></td>
				<td><%= @airplane.price if @airplane.price %></td>
			</tr>
		</tbody>
	</table>

  <p class=" text-danger py-5"><strong>Please fill the below information to continue booking.</strong> </p>
  <hr>
	<div class="login-form">
		<%= form_tag(book_path, method: "get") do %>
		<%= hidden_field_tag "booking[airplane_id]", @airplane.id %>
		<div class="sign-in-htm">
			<div class="group">
				<label for="name" class="label">Your Name</label>
				<%= text_field_tag "booking[name]","",{class: "input"} %>
			</div>
			<div class="group">
				<label for="age" class="label">Age</label>
				<%= text_field_tag "booking[age]","",{class: "input"} %>
			</div>
			<div class="group">
				<label for="passport_id" class="label">Passport/ID</label>
				<%= text_field_tag "booking[passport_id]","",{class: "input"} %>
			</div>
			<div class="group">
				<%= submit_tag "Submit", {class: "button"} %>
			</div>
			<div class="hr"></div>
		</div>
		<%end%>	
	</div>
</div>

app/views/airplanes/ticket.html.erb
HI

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flight</title>
  <%= csp_meta_tag %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'application', '/stylesheets/flight.css' %>
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
</head>

<body>
  <!-- Navigation -->
  <div class="menu">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
      <div class="container">
        <a class="navbar-brand" href="/">
          <p>Navin's Flight</p>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <%= form_tag(search_path, method: "get") do %>
        <%#= text_field_tag "search","",{placeholder: "Search.."} %>
        <%= text_field_tag :search, params[:search] %>
        <%end%>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li>
              <% if current_user %>
              <span class="text-white">
                <%if current_user.type == "UserAdmin"%>
                Welcome Admin : <strong><%= current_user.email %></strong></span> |
                <%else%>
                Logged in as <strong><%= current_user.email %></strong></span> |
                <%end%>
                <%= link_to "Logout", logout_path, :class => 'navbar-link' %> |
                <%if current_user.type == "UserAdmin"%>
                <%= link_to "New Flight", airplanes_path, :class => 'navbar-link' %>
                <%else%>
                <%= link_to "Book Tickets", airplanes_path, :class => 'navbar-link' %>
                <%end%>
                <% else %>
                <%= link_to "Login", login_path, :class => 'navbar-link' %> |
                <%= link_to "Sign Up", new_user_path, :class => 'navbar-link' %>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </div>
    <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
    <div class="foot-lnk">
      <p>Developed by : <i class="fa fa-envelope" aria-hidden="true"></i> <a href="mailto:navinkumar2508@gmail.com"><strong>navinkumar2508@gmail.com</strong></a></p>
    </div>
  </body>
  </html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
<head>
<title>PDF</title>
  <%= wicked_pdf_stylesheet_link_tag "application" -%>
</head>
<body>
  <div class='container'>
    <%= yield %>
  </div>
</body>
</html>

app/views/users/home.html.erb
<p class="text-dark py-5 text-center">Flights - New Year Eve - 2019</p>
<p class="text-dark py-5 text-center"><strong>Welocome to Navin's Flight! You can book here flights available with us at affordable price.</strong><i class="fa fa-plane" style="font-size:36px;"></i> </p>
<p class="text-success py-5 text-center"><strong>Early bird offer get an discount of 10% on your flight bookings.</strong> <i class="fa fa-users" style="font-size:48px;color:green"></i></p>
<hr>
<div class="container">
	<div class="row">
		<%if current_user && current_user.type == "UserAdmin"%>
		<div class="col">
			<%= link_to "New Flight", new_airplane_path, :class => 'btn btn-warning btn-block' %>
		</div>
		<%end%>
		<div class="col">
			<%= link_to "New Booking", airplanes_path, :class => 'btn btn-success btn-block' %>
		</div>

	</div>
</div>

app/views/users/index.html.erb
<p class=" text-info py-5 text-center"><strong>Available Flights.</strong> </p>

app/views/users/new.html.erb
<div class="login-wrap">
	<div class="login-html">
		<input id="tab-1" type="radio" name="tab" class="sign-in" checked><label for="tab-1" class="tab">Sign Up</label>
		<input id="tab-2" type="radio" name="tab" class="for-pwd"><label for="tab-2" class="tab">Sign In</label>
		<div class="login-form">
			<%= form_tag(users_path, method: "new") do %>
			<div class="sign-in-htm">
				<div class="group">
					<label for="user" class="label">Name</label>
					<%= text_field_tag "user[name]","",{class: "input"} %>
				</div>
				<div class="group">
					<label for="user" class="label">Email</label>
					<%= text_field_tag "user[email]","",{class: "input"} %>
				</div>
				<!-- <div class="group">
					<label for="user" class="label">Phone</label>
					<%#= text_field_tag "user[phone]","",{class: "input"} %>
				</div> -->
				<div class="group">
					<label for="pass" class="label">Password</label>
					<%= password_field_tag "user[password]","",{class: "input"} %>
				</div>
				<div class="group">
					<%= submit_tag "Sign Up", {class: "button"} %>
				</div>
				<div class="hr"></div>
			</div>
			<%end%>
			<div class="for-pwd-htm">
				<%= form_tag(users_path, method: "get") do %>
				<div class="group">
					<label for="user" class="label">Email</label>
					<%= text_field_tag "user[email]","",{class: "input"} %>
				</div>
				<div class="group">
					<label for="user" class="label">Password</label>
					<%= password_field_tag "user[password]","",{class: "input"} %>
				</div>
				<div class="group">
					<%= submit_tag "Sign In", {class: "button"} %>
				</div>
				<%end%>
				<div class="hr"></div>
			</div>	
		</div>
	</div>
</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/verify_login.html.erb
<div class="login-wrap">
	<div class="login-html">
		<input id="tab-1" type="radio" name="tab" class="sign-in" checked><label for="tab-1" class="tab">Sign In</label>
		<div class="login-form">
			<%= form_tag(users_path, method: "get") do %>
			<div class="group">
				<label for="user" class="label">Email</label>
				<%= text_field_tag "user[email]","",{class: "input"} %>
			</div>
			<div class="group">
				<label for="user" class="label">Password</label>
				<%= password_field_tag "user[password]","",{class: "input"} %>
			</div>
			<div class="group">
				<%= submit_tag "Sign In", {class: "button"} %>
			</div>
			<div class="hr"></div>
			<%end%>
		</div>

	</div>
</div>